name: paintdotnet
version: '1.0.0'
summary: Paint.NET, an image editor made in .NET
description: |
  Paint.NET is an application created for Windows designed for simple image editing. It has been ported to an unofficial community snap using Wine.
grade: stable
icon: snap/gui/logo.png

base: core22
confinement: strict

parts:
  sommelier-core:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git
    source-branch: "1.0"

plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-5-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-5-stable

apps:
  paintdotnet:
    extensions: [gnome-3-28]
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: C:\Program Files\paint.net\PaintDotNet.exe
      # the official install files are all ZIP files, so I've extracted the ZIP to give us an actual installer
      # comes from https://github.com/paintdotnet/release/releases
      INSTALL_URL: https://github.com/colleirose/colleirose/blob/main/paint.net.5.0.13.install.anycpu.web.exe
      INSTALL_FLAGS: /silent
    plugs:
    - home
    - network
    - network-bind
    - removable-media
  wine:
    extensions: [gnome-3-28]
    command: bin/sommelier
    plugs:
      - home
      - network
  winetricks:
    extensions: [gnome-3-28]
    command: bin/sommelier winetricks
    plugs:
      - home
      - network